### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by boyfromhell** [jantinnerezo/livewire-alert#1]
if you redirect to a page not show.
same page is good
``` php
$this->alert('success', 'Login!');
        return redirect(route('home'));
```

**Comment by jantinnerezo** [comment]
Hey @boyfromhell it's currently not supported for redirects and page reload but I think of considering to add a support for it. Thanks!

**Comment by Jabirr** [comment]
@jantinnerezo Any update on this?

**Comment by jantinnerezo** [comment]
Hi @Jabirr , there is a new feature `flash` method for handling redirect messages.
