### ISSUE TITLE
Erro method flash

### ISSUE THREAD

**Issue by lucasantoniooficial** [jantinnerezo/livewire-alert#10]
Error: BadMethodCallException
Method App\Http\Livewire\Admin\User\Edit::flash does not exist.
http://coaching.test/livewire/message/admin.user.edit
Hide solutions
Bad Method Call

Did you mean App\Http\Livewire\Admin\User\Edit::fill() ?

LiveWire: 2.x
Laravel 8

`public function update()
    {
        $this->user->update($this->validate());

        if(count($this->user->roles) > 0) {
            $this->user->roles()->detach($this->permission);
        }
        $this->user->roles()->attach($this->permission);

        $this->flash('success', 'Usuário editado com sucesso');

        return redirect()->to('/admin/users');

    }`

**Comment by jantinnerezo** [comment]
Hi @lucasantoniooficial, tested on Livewire 2.0 and Laravel 8, did you update the package to 2.0.1?

**Comment by lucasantoniooficial** [comment]
> Olá @lucasantoniooficial , testado em Livewire 2.0 e Laravel 8, você atualizou o pacote para 2.0.1?

"jantinnerezo/livewire-alert": "^2.0",

**Comment by lucasantoniooficial** [comment]
I did the update and it's working!
