### ISSUE TITLE
Uncaught (in promise) ReferenceError: Swal is not defined

### ISSUE THREAD

**Issue by bucari** [jantinnerezo/livewire-alert#104]
I installed livewire-alert publishing livewire-alert.js and added 

<script src="{{ asset('vendor/livewire-alert/livewire-alert.js') }}"></script> 
<x-livewire-alert::flash />

to app.blade.php after  @livewireScripts but i get this error  Uncaught (in promise) ReferenceError: Swal is not defined

**Comment by zsoltjanes** [comment]
I had the same issue
`npm install sweetalert2`

In app.js include it:
```
import swal from 'sweetalert2';
window.Swal = swal;
```

**Comment by madurapa** [comment]
@zsoltjanes not working with flash() method when redirecting
