### ISSUE TITLE
Load trait by default

### ISSUE THREAD

**Issue by garbinmarcelo** [jantinnerezo/livewire-alert#106]
Hello, my question would be to check the possibility of loading this package by default in all components without the need to import and use in each component.

Would it be possible? If yes, how could you do it?

Thank you for your attention and for this package, it is very practical and useful.

**Comment by MDylan** [comment]
Just create a livewire component like:
`php artisan make:livewire BaseComponent`

After it, place all needed trait and components in it, what you want to use example:

```
namespace App\Http\Livewire;

use Livewire\Component;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class BaseComponent extends Component
{
    use LivewireAlert;

}
```

And after you create any other livewire class, just modify the used extended class like:

```
use App\Http\Livewire\BaseComponent;

class ListUsers extends BaseComponent
{
...
}
```
