### ISSUE TITLE
xss atack

### ISSUE THREAD

**Issue by TimurTurdyev** [jantinnerezo/livewire-alert#117]
The documentation contains a link to the package //cdn.jsdelivr.net/npm/sweetalert2@11 which makes the injection https://github.com/sweetalert2/sweetalert2/blob/8854f295cf296026a4e090daf943895232342abd/src/SweetAlert.js#L261
and inserts the anthem of Ukraine for users from Russia

**Comment by gally90** [comment]
> The documentation contains a link to the package //cdn.jsdelivr.net/npm/sweetalert2@11 which makes the injection https://github.com/sweetalert2/sweetalert2/blob/8854f295cf296026a4e090daf943895232342abd/src/SweetAlert.js#L261 and inserts the anthem of Ukraine for users from Russia

Nice
