### ISSUE TITLE
Alert not showing in version 2.0

### ISSUE THREAD

**Issue by moneya** [jantinnerezo/livewire-alert#12]
i recently updated livewire alert from version 1.x to 2.X,
@livewireAlertScripts was switched to <x-livewire-alert::scripts/>
And i removed the livewire alert  trait from my components cause it throws an error when using the trait.
`cannot use Jantinnerezo\LivewireAlert\LivewireAlert - it is not a trait `
to show notification i use the function 
` $this->alert('success', 'Success Message');`
but nothing is shown.

I use the latest version of livewire 2.x
and laravel 7

**Comment by jantinnerezo** [comment]
Hi @moneya,  it's so weird, did you try clearing up the views?

**Comment by moneya** [comment]
![image](https://user-images.githubusercontent.com/7353773/99825242-10446900-2b57-11eb-9f20-623c3e480dd4.png)
This is my function

Below is the wire:click trigger for the function

![image](https://user-images.githubusercontent.com/7353773/99825890-ed668480-2b57-11eb-8610-de0814d6d749.png)


> 
> 
> Hi @moneya, it's so weird, did you try clearing up the views?

I have done that multiple times still the same issue.

**Comment by jantinnerezo** [comment]
Thanks @moneya, what version is your livewire alert now in your composer.json?

**Comment by moneya** [comment]
> Thanks @moneya, what version is your livewire alert now in your composer.json?

@jantinnerezo
 Livewire Alert 2.0.2

Livewire 2.3. 2

**Comment by jantinnerezo** [comment]
Can you try uninstalling and re-installing livewire alert?

**Comment by moneya** [comment]
@jantinnerezo  will do that as soon as I get home.
Thanks.

**Comment by jantinnerezo** [comment]
Great! Thanks @moneya

**Comment by moneya** [comment]
@jantinnerezo Still doesn't work,
Am starting a new install of laravel 8 and test again

**Comment by moneya** [comment]
@jantinnerezo works good in laravel 8 and a fresh install of laravel 7.
maybe something is wrong with my project.
Will port to 8 and try again

**Comment by jantinnerezo** [comment]
Good to know @moneya, did you put the component <x-livewire-alert::scripts/> after @livewireScripts?

**Comment by moneya** [comment]
I did that after the livewire script.


The issue isn't from your package, it's from the app.

I tested in fresh install laravel 7 and 8
Everything is good.

Sorry to bother you chief.

Am closing this issue now.
