### ISSUE TITLE
Livewire 3 Upgrade

### ISSUE THREAD

**Issue by Zakarialabib** [jantinnerezo/livewire-alert#121]
since livewire 3 is out, the package isn't compatible with the latest version

**Comment by jantinnerezo** [comment]
WIP [feat/livewire-3-beta-support](https://github.com/jantinnerezo/livewire-alert/tree/feat/livewire-3-beta-support)

**Comment by wbetalleluzd** [comment]
How install this version?

**Comment by wbetalleluzd** [comment]
> WIP [feat/livewire-3-beta-support](https://github.com/jantinnerezo/livewire-alert/tree/feat/livewire-3-beta-support)

How install this version?

**Comment by jantinnerezo** [comment]
``` bash
composer require jantinnerezo/livewire-alert:^3.0@beta
```
You can check this beta support release 
[v3.0@beta](https://github.com/jantinnerezo/livewire-alert/releases/tag/v3.0%40beta)
