### ISSUE TITLE
Console showing error

### ISSUE THREAD

**Issue by xBigDaddyx** [jantinnerezo/livewire-alert#123]
Hi! i found error on console, please kindly help because i dont understand what is wrong with that. Thanks!
![image](https://github.com/jantinnerezo/livewire-alert/assets/10373528/975a62a9-156e-422b-88c1-669d3208dc14)

**Comment by jantinnerezo** [comment]
Curious, how your setup looks like?

**Comment by technetist** [comment]
I ran into this same error and resolved it.

 I had my array key as `onConfirm` when it should have been `onConfirmed`:

```php
$this->alert('warning', 'Doing something!', [
    ///
    'showConfirmButton' => true,
    'onConfirmed' => 'doSomething',
    ///
]
```
