### ISSUE TITLE
New release requires Livewire V2???

### ISSUE THREAD

**Issue by phadaphunk** [jantinnerezo/livewire-alert#127]
Your new release v3 requires livewire v2 so it crashes our deployment.

**Comment by aeq-dev** [comment]
+1 
What's this ?!

**Comment by aeq-dev** [comment]
I removed it since it breaks my code :/

**Comment by AlexanderTolson** [comment]
+1

**Comment by tarekmag** [comment]
+1

**Comment by mwndigital** [comment]
+1

**Comment by aeq-dev** [comment]
This is a good alternative :) 
composer require realrashid/sweet-alert

**Comment by jantinnerezo** [comment]
Oh shoot, apologies for the oversight I published a new release v3.0.1.

**Comment by phadaphunk** [comment]
The dangers of releasing on a Friday 13th. 💀 

Thanks for the fix it works fine now!
