### ISSUE TITLE
Support multiple alerts on same page

### ISSUE THREAD

**Issue by matsava** [jantinnerezo/livewire-alert#13]
Currently when you have multiple alerts no matter which one you click it always fire the last onConfirmed method in your view. Any plans on supporting this?

**Comment by jantinnerezo** [comment]
Yeah planning to have support for this on the next release.

**Comment by jantinnerezo** [comment]
Already added a support for it in [2.1 release](https://github.com/jantinnerezo/livewire-alert/releases/tag/2.1)
