### ISSUE TITLE
Take an ID as a parameter

### ISSUE THREAD

**Issue by bar00ng** [jantinnerezo/livewire-alert#132]
Hey I'm having trouble to passing an ID of my model to the onConfirmed function. can you guide me?? If u want i can provide you my code.

**Comment by rickt96** [comment]
I've faced this issue too.
When calling $this->alert() or $this->confirm() function, you can set in the third parameter $options a data array, like this:
```
$this->confirm("Are you sure?", [
    'onConfirmed' => "confirmed",
    'data' => [
        'post_id' => $postId
    ]
]);
```

Then, in the confirmed function handler:
```
public function confirmed($data)
{
    $postId = Arr::get($data, 'data.post_id', null);
    // other code
}
```

**Comment by bar00ng** [comment]
wow this is so useful bro!! thank you so much!!
