### ISSUE TITLE
why sweetalert2 is a requirement and not a dependency?

### ISSUE THREAD

**Issue by jigar-dhulla** [jantinnerezo/livewire-alert#135]
Those using this package, will have to make sure that APIs are in sync in future. Probably it's not much to maintain from project stand point. 

But it can be confusing for future devs who are upgrading esp. frontend wondering who is using sweetalert2.

**Comment by jigarakatidus** [comment]
Before I start working on a PR, I want to understand the thought process of keep Swal independent.

**Comment by jigar-dhulla** [comment]
Not important.
