### ISSUE TITLE
Call to undefined method alert

### ISSUE THREAD

**Issue by miladevs** [jantinnerezo/livewire-alert#14]
Hi,

I have installed the package, however I'm encountering a call to undefined method error.  The same happens with the flash method. 

My IDE does autocomplete the package classes, so it's definitely installed correctly. 

`Call to undefined method App\Actions\Story\CreateNewStory::alert()`

I'm using this in `$this->alert('success', 'Story submitted for approval.');`

Any suggestions? :) 

I have followed the instructions as per the GitHub ReadMe and have placed <x-livewire-alert::scripts /> after @livewireScripts.

```
"jantinnerezo/livewire-alert": "^2.0",
        "laravel/framework": "^8.12",
        "livewire/livewire": "^2.0"
```

Thank you!

Mila

**Comment by jantinnerezo** [comment]
Hi @miladevs, you can only call it inside a livewire component class.

My suggestion is call the function after the execution of CreateNewStory action inside your livewire component.
