### ISSUE TITLE
how to send the callback function

### ISSUE THREAD

**Issue by imagina** [jantinnerezo/livewire-alert#15]
hey, i need to send the callback function in to the options, but, i'm not sure how it should be, this is possible from livewire component class ? can you help me with some example ? please
and thanks.

**Comment by jantinnerezo** [comment]
Hi @imagina, what do you mean adding a callback function in to the options? Can you show me a code snippet?

**Comment by imagina** [comment]
Hi @jantinnerezo, i specifically need to do something with the event click of the confirmation button and with the cancel button, now I have simply sent configuration parameters like the documentation https://github.com/jantinnerezo/livewire-alert#configuration, is there any way to configure which event to trigger when they are clicked ?,

**Comment by jantinnerezo** [comment]
Hello @imagina, you can do it like this:

`<x-livewire-alert::confirm onConfirmed="onConfirmedAction" onCancelled="onCancelledCallBack" />`
