### ISSUE TITLE
How to delete record

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [jantinnerezo/livewire-alert#17]
In my blade, I include this line `<x-livewire-alert::confirm onConfirmed="onConfirmedAction" nCancelled="onCancelledCallBack"/>`

now what will be the code for delete.?

If anybody gives some demo then it will be very helpful.

how can I pass the `$id` inside `onConfirmedAction` 

### In blade

```blade
<a class="dropdown-item" wire:click.prevent="destroy({{ $customer->id }})" href="#">
  <i class="bx bx-trash mr-1"></i> delete
</a>
```

### Inside component

```php
public function destroy($id)
{
   $this->confirm('Are you sure?', [
      'text' => 'You are about to delete something'
   ]);

   Customer::query()->findOrFail($id)->delete();

   $this->alert('success', 'Customer has been deleted..!');
}

public function onConfirmedAction()
{
    // what will be the code here.?
}

public function onCancelledCallBack()
{
   // what will be the code here.?
}
```

**Comment by jantinnerezo** [comment]
Hi @ShekhSaifuddin007, take a look at this edited code. You can declare a $customer public property and assign it when you attempt destroy, reset it when click cancel.

```php

public $customer;

public function destroy($id)
{
   $this->confirm('Are you sure?', [
      'text' => 'You are about to delete something'
   ]);

   $this->customer = Customer::query()->findOrFail($id);
}

public function onConfirmedAction()
{
    $this->customer->delete();
      
    $this->alert('success', 'Customer has been deleted..!');
}

public function onCancelledCallBack()
{
    // Reset customer
    $this->reset('customer');
}
```

**Comment by ShekhSaifuddin007** [comment]
@jantinnerezo yes it works, thank you brother...

**Comment by LordEliseus** [comment]
Livewire sweet alert don't working for me .. i'm using stack TALL

**Comment by ShekhSaifuddin007** [comment]
@LordEliseus make sure you add this line `<x-livewire-alert::confirm onConfirmed="onConfirmedAction" nCancelled="onCancelledCallBack"/>` in your livewire components

**Comment by LordEliseus** [comment]
Yes..I found my error.. it's a root tag error..in livewire component.
Thanks..

**Comment by alighasemzadeh** [comment]
@jantinnerezo 
I think it would good idea to add this into document.
