### ISSUE TITLE
Butons language

### ISSUE THREAD

**Issue by nam-co** [jantinnerezo/livewire-alert#22]
Hi, thanks for the work on this package, looks great, I was wondering if its possible to change the language and text of the buttons?
Thanks for the help

**Comment by jantinnerezo** [comment]
Hi @nam-co, I think you use [laravel localization](https://laravel.com/docs/8.x/localization) for that.

**Comment by jantinnerezo** [comment]
```php
$this->alert('success', 'Hello World!', [
      'confirmButtonText' =>  __('messages.confirmText'),
      'cancelButtonText' => __('messages.cancelText')
]);
```

**Comment by nam-co** [comment]
Thanks Jantinn, excellent.
I was wondering is there any way to use this package outside livewire, in a regular controller?

**Comment by jantinnerezo** [comment]
I'm afraid to say that this package is only a SweetAlert2 wrapper for livewire components @nam-co

**Comment by nam-co** [comment]
Thanks for the fast response, it could be great for v2, a wrapper to work on controllers, this way you can use it everywhere with the same include js/css, no need for another package (just an idea).

Once again, thanks for you help J
