### ISSUE TITLE
Unable to install livewire alert

### ISSUE THREAD

**Issue by moneya** [jantinnerezo/livewire-alert#23]
I am trying to install livewire alert in laravel 8.20.1 but i came across this error
![image](https://user-images.githubusercontent.com/7353773/103619311-c8747800-4f31-11eb-880c-2c413efa4235.png)

**Comment by jantinnerezo** [comment]
Hi @moneya can you try installing on dev-master? Let me know if this works so that I can draft a release for it.

```bash
composer require jantinnerezo/livewire-alert:dev-master
```

Thank you for submitting the issue.

**Comment by moneya** [comment]
Ok, let me try that

**Comment by moneya** [comment]
Installed with no issue but i saw this exception
![image](https://user-images.githubusercontent.com/7353773/103621635-cca29480-4f35-11eb-9f0d-a523a99d6865.png)

**Comment by moneya** [comment]
The first issue , creating an empty class seems to fix the error show on install

Take a look at this.
https://github.com/jantinnerezo/livewire-alert/compare/master...moneya:master

**Comment by jantinnerezo** [comment]
Yeah it did fix the issue, I recently deleted the class but you just encountered this issue now. Let me merge that.

**Comment by jantinnerezo** [comment]
Can you create a pull request?

**Comment by moneya** [comment]
> 
> 
> Can you create a pull request?

Right away

**Comment by moneya** [comment]
seems you did already.
Issue fixed.
