### ISSUE TITLE
Alerts not shown on redirect.

### ISSUE THREAD

**Issue by Jabirr** [jantinnerezo/livewire-alert#25]
Hey great package.

It looks really good, i was just wondering when you will add support for showing alerts on redirect. 
Livewire is supporting this feature and I was wondering if you could maybe look into that and use it for your alerts.

![image](https://user-images.githubusercontent.com/31471200/105209428-1b614880-5b4a-11eb-8ea2-ba221103b665.png)

Kind regards,
Jabir

**Comment by jantinnerezo** [comment]
Hello @Jabirr, it's already supported and the method is `flash` you can then call it like this one:

```php
$this->flash('success', 'Hello World!');

return redirect()->to('/') 
```

**Comment by Jabirr** [comment]
Thank you a lot @jantinnerezo, maybe you could add this in the docs?

**Comment by jantinnerezo** [comment]
Yes you can play around with the config on the docs, it'll generate the code for you.

**Comment by pirmax** [comment]
I've an error with flash message.

```
$this->flash('success', 'Article mis à jour !');
return redirect()->route('admin.posts.edit', $this->post);
```

The flash message not working, I've not the flash message...

**Comment by jantinnerezo** [comment]
Hey @pirmax,  did you include the sweetalert2 script?

**Comment by pirmax** [comment]
> Hey @pirmax, did you include the sweetalert2 script?

Yes, the `$this->alert` works but not for `$this->flash`...

**Comment by jantinnerezo** [comment]
Oh I see, currently have no idea to make it work without the defer attribute because it's inline script specially the script for flash, I'll take a look on this and experiment this weekend.

**Comment by sxshateri** [comment]
any idea when this issue will be resolved and merged with the master branch?

**Comment by RishabSwift** [comment]
Any status on this? Having the same issue. I am not able to put `defer` on my script tag.
