### ISSUE TITLE
Unexpected token '?' on Safari

### ISSUE THREAD

**Issue by imagina** [jantinnerezo/livewire-alert#27]
We have the follow js error on Safari browser:

SyntaxError: Unexpected token '?'

![image](https://user-images.githubusercontent.com/758247/106640930-a3851c00-6554-11eb-838d-23f78792c677.png)
However, in Chrome doesn't apper,
Thanks.

**Comment by jantinnerezo** [comment]
What is your current safari version?

**Comment by imagina** [comment]
Versión 13.0.1 (14608.2.11.1.11)

**Comment by jantinnerezo** [comment]
Hi @imagina, it seems that your version of safari doesn't support **null coalescing operator**. Let me try some fallback for this, sorry for the very late reply been busy this past few days.

**Comment by IP-Developer** [comment]
I can confirm that this is a common issue (based on our production errors tracking)

**Comment by Grimthorr** [comment]
Fixed in #40 (using dev-master#94a583dbd689a9a613349ec2dd8703081684aa3a).

**Comment by jantinnerezo** [comment]
Hello guys, please update to [2.1.7](https://github.com/jantinnerezo/livewire-alert/releases/tag/2.1.7). Sorry it took time to publish the release.
