### ISSUE TITLE
Flash issue

### ISSUE THREAD

**Issue by youngtype** [jantinnerezo/livewire-alert#28]
![image](https://user-images.githubusercontent.com/79363260/108605901-9d4dc700-73bf-11eb-874e-919102da8d1f.png)

Please help me with that error

**Comment by youngtype** [comment]
If delete this string `$options = array_merge(config('livewire-alert.alert'), $options);` it will works but without options, so how to fix that issue 🤣 ?)

**Comment by jantinnerezo** [comment]
Nice! @youngtype, should have a fix on the next release. Thank you @youngtype

**Comment by adistoica** [comment]
@jantinnerezo I'm having the same issue as @youngtype. Would you be kind to provide a fix? :)

**Comment by jantinnerezo** [comment]
Fixed on [2.1.5 release](https://github.com/jantinnerezo/livewire-alert/releases/tag/2.1.5)

Apologies for the late response

**Comment by salvomil** [comment]
Hi, I got error on confirm alert:

![error_livewire_alert](https://user-images.githubusercontent.com/16554089/111678014-1c4be900-8820-11eb-979b-625ddc91683c.png)


My Code:
` 
protected $listeners = ['cancelled', 'createNewProduct'];
...
...
...

public function triggerConfirm() {
        $confirmCreate = $this->confirm([
            'title' => 'Attenzione',
            'text' => "Un prodotto con questo codice a barra non esiste in anagrafica prodotti, vuoi crearlo?",
            'icon' => 'warning',
            'showCancelButton' => true,
            'confirmButtonColor' => '#3085d6',
            'cancelButtonColor' => '#d33',
            'confirmButtonText' => 'Sì, crealo!',
            'onConfirmed' => 'createNewProduct',
            'onCancelled' => 'cancelled'
        ]);
    }

public function createNewProduct() {
        dd('Creazione nuovo prodotto');
    }

`


In another component I got the confirm ok.

**Comment by jantinnerezo** [comment]
Hello there @salvomil, you are missing the first argument of the method `$this->confirm`.

It should be like this:

``` php
$confirmCreate = $this->confirm('Attenzione', [
'title' => 'Attenzione', // Move this as the first argument
'text' => "Un prodotto con questo codice a barra non esiste in anagrafica prodotti, vuoi crearlo?",
'icon' => 'warning',
'showCancelButton' => true,
'confirmButtonColor' => '#3085d6',
'cancelButtonColor' => '#d33',
'confirmButtonText' => 'Sì, crealo!',
'onConfirmed' => 'createNewProduct',
'onCancelled' => 'cancelled'
]);
```

Let me know if that works, thanks for reporting an issue @salvomil !
