### ISSUE TITLE
Maybe I miss something...

### ISSUE THREAD

**Issue by lucaciotti** [jantinnerezo/livewire-alert#31]
Hi, 
I would very much like to use this package.
I am developing a webapp with laravel and adminlte.

I wanted to integrate your package ... but I can't show this test ...

I imported everything correctly ... sweetalert2 works well outside the livewire component...

---- livewire extended class
`
  class MailSendTest extends Component {   
      protected $listeners = [
      'confirmed',
      'cancelled',
      ];
  
      public function render()
      {
          return view('livewire.test.mail-send-test');
      }
  
      public function confirmed()
      {
          Mail::raw('Hi, welcome user!', function ($message) {
              $message->to(Auth::user()->email)->subject('Test');
          });
          
          $this->alert('success', 'Ok! Mail Sended', [
              'position' =>  'top-end',
              'timer' =>  3000,
              'toast' =>  true,
              'text' =>  'Check out!',
              'confirmButtonText' =>  'Ok',
              'cancelButtonText' =>  'Cancel',
              'showCancelButton' =>  true,
              'showConfirmButton' =>  false,
          ]);
      }
  
      public function cancelled()
      {
          $this->alert('info', 'No email sended!');
      }
  
      public function triggerConfirm()
      {
          $this->confirm('Would you send a test email?', [
              'toast' => false,
              'position' => 'center',
              'showConfirmButton' => true,
              'cancelButtonText' => 'Nope',
              'onConfirmed' => 'confirmed',
              'onCancelled' => 'cancelled'
          ]);
          Log::info('ok end');
      }
  }
`

---- livewire view

`< div>
    < button class="btn btn-block btn-outline-warning" wire:click='triggerConfirm'>
       < i class="fas fa-at"></i> Send Email
    </ button>
</ div>`

**Comment by jantinnerezo** [comment]
Hmm how did you import `<x-livewire-alert::scripts />` and sweetalert2 scripts? 

Thank you opening up an issue by the way @lucaciotti

**Comment by lucaciotti** [comment]
Oops...
I was missing just that...

Thank you @jantinnerezo 

You can delete this post if you think so...cause is not really an issue
