### ISSUE TITLE
Is it possible to call the flash method in the controller?

### ISSUE THREAD

**Issue by zhi8617** [jantinnerezo/livewire-alert#35]
Sometimes it's not always necessary to be in Livewire component,  just need redirects and flash messages.
I've found that the code can probably be placed inside the session, is there a cleaner way?

English is not my native language, please forgive my poor grammar.
Thank you for making this beautiful package!

**Comment by jantinnerezo** [comment]
I'm afraid to say this but this package is specifically for livewire components only @zhi8617

**Comment by nam-co** [comment]
Hi @zhi8617 , probably you can do something like this:

Controller
```
session()->push('alerts', ['type' => 'error', 'message' => 'Something']);
```

In Component
```
if (session()->has('alerts')) {
  foreach (session('alerts') as $alert) {
    $this->alert($alert['type'], $alert['message']);
  }
  session()->forget('alerts');
}
```

What do you think @jantinnerezo ?

**Comment by nam-co** [comment]
@zhi8617 it seems you can also just do this:

in Controller
```
session()->flash('livewire-alert', ['type' => 'error', 'message' => 'Something']);
```

But is not a toast
