### ISSUE TITLE
Unable to resolve dependency [Parameter #0 [ <required> $id ]]

### ISSUE THREAD

**Issue by dukenst2006** [jantinnerezo/livewire-alert#38]
I get this error When trying to get the ID parametter to delete a post 
`Unable to resolve dependency [Parameter #0 [ <required> $id ]]`
```
// function to delete the post
public function confirmed($id){
        dd($id);
}
```
```
//Confirmation message 
public function remove($id)
    {
        $this->confirm('Do you want to delete post?', [
            'toast' => false,
            'position' => 'center',
            'showConfirmButton' => true,
            'cancelButtonText' => 'Nope',
            'inputAttributes' => ["id"=>$id],
            'onConfirmed' => 'confirmed',
            'onCancelled' => 'cancelled'
        ]);
    }
```
Any idea how i can get the ID parameter to be able to delete the post when user confirmed ?

**Comment by jantinnerezo** [comment]
Hey @dukenst2006, please update to 2.1.6. Thank you!

**Comment by dukenst2006** [comment]
Hi @jantinnerezo update to 2.1.6 and still have the same issue, even if i clear cache etc ...

**Comment by jantinnerezo** [comment]
Did you try `php artisan view:clear` ?

**Comment by Majid-Bhatti** [comment]
Unable to resolve dependency [Parameter #0 [ <required> $products ]] in class App\Jobs\ProductSaveProcess (This is my error During when i dispatch my job then this show. My handel function is given below.

IN My Controller were i dispatch 👍 
ProductSaveProcess::dispatch($chunks[0]);

 public function handle($products)
    {
        Log::info(print_r($products,true));
        foreach ($products as $product){
            if ($product){
                Product::updateOrCreate(
                    [
                        'stock_code' => $product['StockCode'],
                    ],
                    [
                        'full_name' => $product['FullName'],
                        'price' => $product['Price'],
                        'unit_price' => 'GBP',
                        'description' => $product['Description'],
                        'quantity' => $product['StockLevel'],
                        'image' => $product['ThumbnailImageUrl'],
                        'barcode' => $product['Barcode'],
                        'size' => $product['Size'],
                        'type' => $product['Type'],
                        'gender' => $product['Gender'],
                        'collection' => $product['Collection'],
                        'category' => $product['Category'],
                        'brand' => $product['Brand'],
                    ]
                );
            }
            $shop = $this->shopify_shop_service->currentShopData();
            $this->shopify_service->createProduct($shop,$product);
        }
    }
