### ISSUE TITLE
Is it possible to have default parameters auto-applied?

### ISSUE THREAD

**Issue by milanchheda** [jantinnerezo/livewire-alert#43]
Hey, 

First of all, thanks for the amazing package.

Is it possible to auto-apply the default configurations from the `livewire-alert.php` config file? In the sense, in my livewire component, we have write the below for the alert:

```
$this->alert('success', 'Hello World!', [
'position' =>  'bottom-end',
'timer' =>  3000,
'toast' =>  true,
'text' =>  '',
'confirmButtonText' =>  'Ok',
'cancelButtonText' =>  'Cancel',
'showCancelButton' =>  false,
'showConfirmButton' =>  false,
]);
```

Can we instead have something like this:
```
$this->alert('success', 'Hello World!');
```

and it auto-applies default configurations for `alert` from the config file?

**Comment by jantinnerezo** [comment]
Hello @milanchheda,  did you try clearing config? 
```
php artisan config:clear
php artisan config:cache
```

**Comment by milanchheda** [comment]
Perfect! That work. Thanks @jantinnerezo! 👍🏼
