### ISSUE TITLE
How to retrieve the value of a textarea?

### ISSUE THREAD

**Issue by Fred7877** [jantinnerezo/livewire-alert#50]
hello ! 
I have : 
 $this->confirm('Envoyer un message à ' . $this->user->pseudo, [
                'toast' => false,
                'position' => 'center',
                'showConfirmButton' => true,
                'showCancelButton' => true,
                'onConfirmed' => 'confirmed',
                'onCancelled' => '',
                'input' => 'textarea',
            ]);
But, How to retrieve the value of the textarea?

Thanks !

**Comment by jantinnerezo** [comment]
Hi @Fred7877 , getting the input value will be added on the next release tomorrow.

**Comment by Fred7877** [comment]
Hi jantinnerezo, thanks for the answer and thanks for this plugin :)

**Comment by jantinnerezo** [comment]
Hi @Fred7877, did you already update to 2.2.1? 

You can already get the value of the alert input and it's also documented.

**Comment by Fred7877** [comment]
Hello @jantinnerezo !
Yes, i have update to 2.2.1 at the moment and it's work very well :)
The Trait it's really convenient.

Congratulations on the work done.

Thanks !!

**Comment by jantinnerezo** [comment]
You're welcome @Fred7877
