### ISSUE TITLE
Update 2.1.9 error

### ISSUE THREAD

**Issue by nam-co** [jantinnerezo/livewire-alert#52]
Hi, I've been using Livewire-alert and it worked excellent, but I just updated to 2.1.9 and starting getting the error "Method App\Http\Livewire\XXXX\XXXX::alert does not exist", so I went to the readme and saw I need it to add this that I didn't have before:
```
use Jantinnerezo\LivewireAlert\WithAlert;
use LivewireAlert;
```
I added them and now Im getting a 
"Trait 'App\Http\Livewire\PageMaker\LivewireAlert' not found"

Appreciate any help
Regards
Michael

**Comment by anthony-brindley** [comment]
Hi Michael, I was getting the same issue. If you look at your code, you need to use use Jantinnerezo\LivewireAlert\LivewireAlert; and then include the trait inside the class. There is no 'WithAlert' include that I can see. I've just done this and the alerts work fine.

e.g

```
<?php

namespace {your-namespace-here}

use Jantinnerezo\LivewireAlert\LivewireAlert;

class {yourClassName} 
{

use LivewireAlert;

//...
```

**Comment by nam-co** [comment]
Hi @anthony-brindley , your solution works, everything is ok now, thanks a lot

**Comment by nam-co** [comment]
Hi @jantinnerezo I just notice the "$this->confirm" shows up, but 'onConfirmed' it doesn't run the function, I. tried changing to ->alert but is the same, the 'onConfirmed' => 'confirmedClearAll' still doesn't work, the listener is in place

Appreciate any help
Regards
Michael

**Comment by jantinnerezo** [comment]
Hi @nam-co, the `WithAlert` is a mistake, forgot to edit in the final draft of README.md when released.

About your concern of the confirm function doesn't run, you need to register the function first to event listeners. 

``` php
protected $listeners = [
  'confirmedClearAll'
];
```
