### ISSUE TITLE
2.2.0  break inputAttribute on confirm

### ISSUE THREAD

**Issue by Wit3** [jantinnerezo/livewire-alert#54]
Hi, with latest release the inputAttribute doesn't work anymore, i try to investigate on these days.

**Comment by jantinnerezo** [comment]
This is already fixed: [`2.2.1`](https://github.com/jantinnerezo/livewire-alert/releases/tag/2.2.1)

**Comment by jantinnerezo** [comment]
Closing this one, Thanks!
