### ISSUE TITLE
SweetAlert2: Unknown parameter "onConfirmed"

### ISSUE THREAD

**Issue by mchisnerman3** [jantinnerezo/livewire-alert#55]
Hi, im from argentina, your componente is awesome, but i have this error:
SweetAlert2: Unknown parameter "onConfirmed"

Can you help me please?

Thanks!!

**Comment by jantinnerezo** [comment]
This is already fixed: [`2.2.1`](https://github.com/jantinnerezo/livewire-alert/releases/tag/2.2.1)

**Comment by mchisnerman3** [comment]
Yes, work fine now!!!
Another question (if it possible)
Can i put a summernote textarea in this alert?
![imagen](https://user-images.githubusercontent.com/21108629/140925691-6b6604ca-a54f-42df-a1dd-bf5e901be052.png)

Replace this with summernote

**Comment by jantinnerezo** [comment]
Unfortunately not yet possible as of now but yep this might be possible in the future. Thanks for the idea! 
Closing this now @mchisnerman3.
