### ISSUE TITLE
$this->alert suddenly not working

### ISSUE THREAD

**Issue by rudolfbruder** [jantinnerezo/livewire-alert#57]
Hello,

Maybe you could give me a quick tip but suddenly this package stopped working, maybe after update (no major version updated right?).

What fixed it is including the:

    use LivewireAlert;

I believe this was not required before and crashed our app. Am i doing something wrong that it worked before?

Thank you!

**Comment by jabxr** [comment]
Hi, I was also trying to downgrade but I don't know what version would be correct. This also broke our app on production.

**Comment by jantinnerezo** [comment]
Hello @rudolfbruder, I move the alert codes to a trait on purpose. 

You can check the release notes on breaking changes: [2.1.9](https://github.com/jantinnerezo/livewire-alert/releases/tag/2.1.9])

**Comment by jantinnerezo** [comment]
Hello @jabxr, the version that automatically registers the alert methods is [2.1.8](https://github.com/jantinnerezo/livewire-alert/tree/2.1.8)

You can check the release notes on breaking changes: [2.1.9](https://github.com/jantinnerezo/livewire-alert/releases/tag/2.1.9])

**Comment by jantinnerezo** [comment]
Closing this one, Thank you
