### ISSUE TITLE
Error sweetAlert2 

### ISSUE THREAD

**Issue by Fred7877** [jantinnerezo/livewire-alert#59]
Hello @jantinnerezo !

I get a sweetAlert2 error in the javascript console when I use alert() or confirm():

sweetalert2@10:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
at i.value (sweetalert2@10:1)

I have tested with sweetalert2@11, same thing.

I don't know if you can do anything or if you know about this mistake...

Regards,

**Comment by jantinnerezo** [comment]
Hi @Fred7877, can you show me how you import sweetalert2 and livewire alert scripts?

**Comment by Fred7877** [comment]
@extends('layouts.admin')

@section('content_header')
    <h1>Utilisateurs</h1>
@stop

@section('content_admin')
    {{$dataTable->table()}}
@stop

@push('js')

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <x-livewire-alert::scripts />

    <script src="{{ asset('vendor/livewire-alert/livewire-alert.js') }}"></script>
    <x-livewire-alert::flash />

    {{$dataTable->scripts()}}

@endpush

**Comment by jantinnerezo** [comment]
You can just either import 
`<x-livewire-alert::scripts />`
 or 
`<script src="{{ asset('vendor/livewire-alert/livewire-alert.js') }}"></script>`

because you are importing the script twice.

You can check the demo repo:
https://github.com/jantinnerezo/livewire-alert-demo/blob/main/resources/views/layouts/master.blade.php

**Comment by jantinnerezo** [comment]
When using `<x-livewire-alert::scripts />`, you don't need to include the `<x-livewire-alert::flash />` anymore.

**Comment by Fred7877** [comment]
Thanks ! it's clear the error message, but i don't get the flash message after redirection 😕

Here the method in Livewire component
```
public function confirmed()
    {
        if ($this->modelIdToRemove === $this->modelId) {
            $this->modelType::find($this->modelIdToRemove)->delete();

            $this->flash('success', 'Successfully deleted', [
                'position' => 'top-end',
                'timer' => 3000,
                'toast' => true,
            ], route('users.index'));
        }
    }
```
And here, the import in bade template
```
@push('js')
    {{$dataTable->scripts()}}

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="{{ asset('vendor/livewire-alert/livewire-alert.js') }}"></script>
    <x-livewire-alert::flash />
@endpush
```

Regards,

**Comment by jantinnerezo** [comment]
Great! closing it now. Thanks!
