### ISSUE TITLE
livewire-alert with ide-helper

### ISSUE THREAD

**Issue by MarkGovor** [jantinnerezo/livewire-alert#6]
Hello, please correct your package

  Cannot instantiate trait Jantinnerezo\LivewireAlert\LivewireAlert

  at C:\Users\Admin\Desktop\web-laravel-8\vendor\jantinnerezo\livewire-alert\src\LivewireAlertServiceProvider.php:63
     59▕         $this->mergeConfigFrom(__DIR__ . '/../config/config.php', 'livewire-alert');
     60▕
     61▕         // Register the main class to use with the facade
     62▕         $this->app->singleton('livewire-alert', function () {
  ➜  63▕             return new LivewireAlert;
     64▕         });
     65▕     }
     66▕ }
     67▕

  1  C:\Users\Admin\Desktop\web-laravel-8\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
      Jantinnerezo\LivewireAlert\LivewireAlertServiceProvider::Jantinnerezo\LivewireAlert\{closure}(Object(Illuminate\Foundation\Application), [])

**Comment by jantinnerezo** [comment]
Hello @MarkGovor, sorry for the response, I haven't use an ide-helper before. Did you tried dump-autoload?
