### ISSUE TITLE
Livewire sweetalert throws BadMethodCallException

### ISSUE THREAD

**Issue by stephen-morlex** [jantinnerezo/livewire-alert#60]
### It was working before now i throws error 
BadMethodCallException
Method App\Http\Livewire\Department\Index::confirm does not exist.

**App Blade **
` @livewireScripts

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <x-livewire-alert::scripts />`
**Code in Department component to delete a department**
`  // Delete confirm method
    public function confirmed()
    {
        $this->department->delete();
        $this->alert(
            'success',
            'Department is deleted.'
        );
    }`

**Comment by jantinnerezo** [comment]
In the latest version I removed alert macros for Livewire component so it would not register the methods automatically and on every livewire components that are not using alert.

You can use the new trait instead.

``` PHP
use Jantinnerezo\LivewireAlert\LivewireAlert;
 
class Index extends Component
{
    use LivewireAlert;
}
```

**Comment by stephen-morlex** [comment]
Great thanks @jantinnerezo  is working now.

**Comment by johnsonsebire** [comment]
I'm doing this but it keeps throwing an error "... cannot use Jantinnerezo\LivewireAlert\LivewireAlert - it is not a trait in file ..." in Laravel 8

What could be wrong? 

use Jantinnerezo\LivewireAlert\LivewireAlert;
 
class Index extends Component
{
    use LivewireAlert;
}

**Comment by stephen-morlex** [comment]
@johnsonsebire did you update the package version?
