### ISSUE TITLE
Livewire component in a loop

### ISSUE THREAD

**Issue by Fred7877** [jantinnerezo/livewire-alert#61]
Hi !
I have a problem when a component is in a loop and 'confirmed' is called by a component because in this case, all the components that listen to 'confirmed' execute the method.

Is there a way to prevent all 'confirmed' methods from being executed?

Regards,

**Comment by jantinnerezo** [comment]
Hi @Fred7877

You can actually choose whatever method name you want for the `onConfirmed` event other than `confirmed`

The good news is in the next `2.2.2` release it should just listen to own events by default and if you want to target specific livewire component only you can do this for performance purposes:

``` PHP
'onConfirmed' => [
   'component' => 'livewire-component',
   'event' => 'confirmed'
]
```

**Comment by Fred7877** [comment]
Yes, I know we can change the confirmed name to something else, the problem is that no matter what the name of the method is, all the components listen to this method and it is therefore triggered by all the components at the same time, if for example, we want to delete an item in a list, all the items will be deleted since the method will be executed by all the components, this is annoying ;)

Version 2.2.2 should solve this problem.

Thanks for the quick response (as always :) )
