### ISSUE TITLE
how to add custom tailwindcss styling to the alerts

### ISSUE THREAD

**Issue by Ticket-Master** [jantinnerezo/livewire-alert#65]
hi,

i tried to use tailwindcss classes in the customClass but it is not being used.

is there any way to achieve it ?

**Comment by jantinnerezo** [comment]
Hi @Ticket-Master,

Can you show me a snippet of how you did it? 

Make sure to also set `buttonStyling` to `false`.

Also, is `JIT` mode is enabled in your `tailwind.config.js`?

**Comment by thetwopct** [comment]
For me it was adding

`'toast' => false,`

then custom CSS worked
