### ISSUE TITLE
Breaking changes should be a new major version

### ISSUE THREAD

**Issue by vlados** [jantinnerezo/livewire-alert#66]
In version 2.1.9 was introduced a new breaking change where we should add trait LivewireAlert to every component using the alert function.
Please in the future warn everybody for such a changes!

**Comment by jantinnerezo** [comment]
Apologies for that @vlados, it was a mistake during the release, should be a major version.

**Comment by vlados** [comment]
Also and confirm function and the config was changed ... Please dont do this
