### ISSUE TITLE
Disable 'bounce' effect?

### ISSUE THREAD

**Issue by samhaiden** [jantinnerezo/livewire-alert#67]
Is there a way to disable the bounce effect when the alert pops up? I'd prefer a simple slide or fade in.. any insight would be much appreciated.

**Comment by jantinnerezo** [comment]
Hi @samhaiden 

You can customize the transition effect by adding your own class to the configuration. 

For show:
``` PHP
[
  'popup' =>  'swal2-show',
  'backdrop' =>  'swal2-backdrop-show',
  'icon' => 'swal2-icon-show'
]
```

For hide:
``` PHP
[
  'popup' => 'swal2-hide',
  'backdrop' => 'swal2-backdrop-hide',
  'icon' =>  'swal2-icon-hide'
]
```

Sorry for the late reply.
