### ISSUE TITLE
Input value doesnt get passed to listener

### ISSUE THREAD

**Issue by rahmanramsi** [jantinnerezo/livewire-alert#68]
Code 
```php
$this->alert('info', 'This is not as toast alert', [
      'toast' => false,
      'position' => 'center',
      'showConfirmButton' => true,
      'showDenyButton' => true,
      'confirmButtonText' => 'Yes',
      'onConfirmed' => 'delete',
      'input' => 'this is the value that doest get passed to the onConfirmed callback',
]);
```

Data that retrieved to confirmed callback
![image](https://user-images.githubusercontent.com/48276043/149439206-bbf2bcab-ff5c-486a-9ad9-935f45a40ff7.png)

**Comment by Xyntax01** [comment]
You can try this:
https://github.com/jantinnerezo/livewire-alert/issues/36#issuecomment-841040439

**Comment by jantinnerezo** [comment]
Hello @rahmanramsi,

`input` property value should be the input type, see SweetAlert2 docs: https://sweetalert2.github.io/#input-types

**Comment by rahmanramsi** [comment]
thanks @Xyntax01  and @jantinnerezo , it work now
