### ISSUE TITLE
Conflict with laravel 8 and livewire 2.0

### ISSUE THREAD

**Issue by MichaelGatuma** [jantinnerezo/livewire-alert#7]
![Screenshot (49)](https://user-images.githubusercontent.com/50529359/95488395-2a0e6000-099e-11eb-914f-7ff650cc215c.png)

### Exception
```
> Livewire\Exceptions\ComponentNotFoundException
> Unable to find component: [navigation-dropdown] 
```
### To regenerate:
1. Install new laravel application with jetstream
`$ laravel new laravelapp --jet`
2. Install livewire-alert
`$ composer require jantinnerezo/livewire-alert`
3. Open dashboard `[http://127.0.0.1:8000/dashboard](http://127.0.0.1:8000/dashboard)`

**Comment by jantinnerezo** [comment]
Hi @MichaelGatuma! Did you create a navigation-dropdown component? I guess you included it somewhere in your views and laravel can't find it.

**Comment by MichaelGatuma** [comment]
Hello @jantinnerezo! That is with the default installation of laravel, so the navigation-dropdown exists, as well as all the other components.
The same exception is thrown for all the components like the two-factor-authentication-form, logout-other-browser-sessions-form etc.
I think it should just work with those without conflicts straight out of the box.

**Comment by jantinnerezo** [comment]
So weird, I haven't encounter that issue when installing it on my laravel 8 with jetstream project.

Did you try clearing the views?

**Comment by MichaelGatuma** [comment]
No, not yet. let me try

**Comment by MichaelGatuma** [comment]
I have cleared everything cached including compiled classes and packages. The error still persists.

**Comment by jantinnerezo** [comment]
@MichaelGatuma I will try reproducing it later tonight with a fresh installation of Laravel + Jetstream.

**Comment by dukenst2006** [comment]
I got this issue as well on Laravel 8 with jetsream, livewire is unable to find any components where LivewireAlert not imported. only the component where i imported LivewireAlert be able to load. all others components messed. after remove the package all worked as expected. thanks to look into the issue.

Best,

**Comment by MichaelGatuma** [comment]
> I got this issue as well on Laravel 8 with jetsream, livewire is unable to find any components where LivewireAlert not imported. only the component where i imported LivewireAlert be able to load. all others components messed. after remove the package all worked as expected. thanks to look into the issue.
> 
> Best,

@jantinnerezo

**Comment by mafalda2007** [comment]
Hi @jantinnerezo, the whole project stopped working after installing the package.

Same error :(
`> Livewire\Exceptions\ComponentNotFoundException
> Unable to find component: [navigation-dropdown] `

**Comment by jantinnerezo** [comment]
Hi guys! sorry for the very late response. I added a new 2.0 release, it should fix the **Livewire\Exceptions\ComponentNotFoundException**

Thank you guys!

**Comment by jantinnerezo** [comment]
Just removed the LivewireAlert trait guys to your livewire components and just use the $this->alert directly

**Comment by mohamedsabil83** [comment]
Return this message: **Unable to locate a class or view for component [livewire-alert::script]**
Laravel 8 without JetStream + Livewire 2

Does this line changed **`<x-livewire-alert::script />`**?

**Comment by mohamedsabil83** [comment]
> Return this message: **Unable to locate a class or view for component [livewire-alert::script]**
> Laravel 8 without JetStream + Livewire 2
> 
> Does this line changed **`<x-livewire-alert::script />`**?

@jantinnerezo The right one is `<x-livewire-alert::scripts />`. I make a PR #8 to update it on the README file

**Comment by jantinnerezo** [comment]
Yeah sorry about that typo, its merged now. Thank you so much!

**Comment by mafalda2007** [comment]
Great! Thanks!

**Comment by MichaelGatuma** [comment]
@dukenst2006 the issue has been resolved. It works fine now. Thanks a lot @jantinnerezo for looking into that! I will now close the issue from my side.
