### ISSUE TITLE
How to handle validation errors with Livewire Alert

### ISSUE THREAD

**Issue by xihad76** [jantinnerezo/livewire-alert#72]
Livewire alert works perfectly as described. But in case of showing validation errors I couldn't think of any way except using a custom validator. Currently, if the validation fails on `$this->validate()`, the alert doesn't fire on the client-side by default. What would be the best approach with livewire alert for showing validation errors?

**Comment by abbasgholia** [comment]
hi
this was already done correctly in version 2.1.
unfortunately I did not have time to modify the new version
fix it if possible
  code for version 2.0:

`
<script>
    "use strict";
  
    window.addEventListener('alert', event => {
        var _event$detail$message, _event$detail$type;

        if((_event$detail$message = event.detail.message) !== null && _event$detail$message !== void 0){

            (_event$detail$message = event.detail.message) !== null && _event$detail$message !== void 0 ? _event$detail$message : '';

            
        var MessageAll =_event$detail$message;
        var AllErrorsConvertToString = '';
        var count=1;

        if( typeof MessageAll === 'object' && MessageAll !=''){
            
            for (const [key, value] of Object.entries(MessageAll)) {
                value.forEach(element => {  
                    AllErrorsConvertToString = AllErrorsConvertToString+"<li class='d-flex align-items-center py-2'><span class='bullet bullet-dot bg-danger me-5'></span> "+element+" </li>"
                   count++; 
                });
            }
          
        }else{
            AllErrorsConvertToString = MessageAll;
        }


                   
        Swal.fire(Object.assign({}, {
            //!== void 0  شناسایی undefined نباشد
            title: AllErrorsConvertToString,
            icon: (_event$detail$type = event.detail.type) !== null && _event$detail$type !== void 0 ? _event$detail$type : null,
        }, event.detail.options));
        }
        

 
    
    });
    window.addEventListener('confirming', confirming => {
        window.addEventListener(confirming.detail, event => {
            var _event$detail$options;

            Swal.fire(Object.assign(
                {}, {
                    confirmButtonText: (_event$detail$options = event.detail.options.confirmButtonText) !== null && _event$detail$options !== void 0 ? _event$detail$options : 'Yes',
                }, event.detail.options
            )).then(result => {
                if (result.isConfirmed) {
                    Livewire.emit(event.detail.onConfirmed, event.detail.options["inputAttributes"]);
                } else {
                    const cancelCallback = event.detail.onCancelled;

                    if (!cancelCallback) {
                        return;
                    }

                    Livewire.emit(cancelCallback);
                }
            });
        });
    });
</script>

@if (session()->has('livewire-alert'))
<script>
    "use strict";

        window.onload = event => {
            var _flash$message, _flash$type;

            const flash = @json(session('livewire-alert'));
            Swal.fire({
                title: (_flash$message = flash.message) !== null && _flash$message !== void 0 ? _flash$message : '',
                icon: (_flash$type = flash.type) !== null && _flash$type !== void 0 ? _flash$type : null,
                ...flash.options
            });
        };
</script>
@endif
`
regard mostafa
