### ISSUE TITLE
Support Laravel 9

### ISSUE THREAD

**Issue by wbetalleluzd** [jantinnerezo/livewire-alert#73]
$ composer require jantinnerezo/livewire-alert
Using version ^2.2 for jantinnerezo/livewire-alert
./composer.json has been updated
Running composer update jantinnerezo/livewire-alert
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jantinnerezo/livewire-alert ^2.2 -> satisfiable by jantinnerezo/livewire-alert[2.2.0, 2.2.1, 2.2.2, 2.2.3].
    - jantinnerezo/livewire-alert[2.2.0, ..., 2.2.3] require illuminate/support ^5.5 || ^6.0 || ^7.0 || ^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require jantinnerezo/livewire-alert:*" to figure out if any version is installable, or "composer require jantinnerezo/livewire-alert:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by jantinnerezo** [comment]
Hello @wbetalleluzd 

Please upgrade to 2.2.4 latest release

**Comment by wbetalleluzd** [comment]
Thank you...!!!!

**Comment by jantinnerezo** [comment]
You're welcome @wbetalleluzd !
