### ISSUE TITLE
Label bug on intro page

### ISSUE THREAD

**Issue by marispro** [jantinnerezo/livewire-alert#77]
Hello,

found small label bug
![Mar-15-2022 11-50-52](https://user-images.githubusercontent.com/5610414/158352003-441e041f-4d70-4135-a017-6d77ab69175e.gif)

and would be nice to include new feature there as well  https://github.com/jantinnerezo/livewire-alert/pull/75

**Comment by jantinnerezo** [comment]
Fixed already, Thanks @marispro!
