### ISSUE TITLE
Passing data to confirmed method

### ISSUE THREAD

**Issue by mrl22** [jantinnerezo/livewire-alert#82]
Hello

First of all, thank you for such an amazing package.

I am creating a confirm delete box and have found (although not documented) that I can put whatever I want in to 'inputAttributes' and get them back out in the confirmed method using $data['data']['inputAttributes'].

Is there a better way to do this, without setting any public variables?

My code:

```
protected $listeners = [
    'confirmedDelete' => 'confirmedDelete'
];
public function delete($ids) {
    $this->confirm('Are you sure you wish to delete? <h4>Associated questions will also be deleted.</h4>', [
        'inputAttributes' => ['ids' => $ids],
        'onConfirmed' => 'confirmedDelete'
    ]);
}
public function confirmedDelete($data) {
    (new QuestionCategoryController())->destroy($data['data']['inputAttributes']['ids']);
}
```

**Comment by jantinnerezo** [comment]
Hello @mrl22 

What do you mean without setting any public variables?

**Comment by mrl22** [comment]
@jantinnerezo I am not the best at my wording. When I say public variables I mean when you put private or public $string; at the top of a class.

I am just trying to make sure I am passing variables the best way.

**Comment by lutfifirdaus** [comment]
Hello @jantinnerezo 

what i get from @mrl22 is maybe there is a way that we can pass data inside `onConfirmed` event like livewire event `emit('someEvent', $model->id)` that can pass data. 

Because i also have similiar problem that when i get no solution about this problem, i approach it by using public or protected variable to store data temporarely from wire:click that has alert() or confirm() sweetalert function...

**Comment by mrl22** [comment]
@lutfifirdaus If I have a table with a list of delete buttons for each record, I wanted to find if there was a feature to pass the record ID to the "confirmedDelete"  listener which will then call a function to delete that record.

I too have tried your way too but I was worried that let's say my client was somehow able to click two delete buttons at the same time which sets the public/protected variable and opens a modal to confirm, it could end up deleting the wrong record.

The project using the demonstrated method above has been tested, signed off and deployed so it proves to work well. But I am using inputAttributes and I could not find in the documentation what inputAttributes SHOULD be used for.

**Comment by lutfifirdaus** [comment]
@mrl22 i also has try that method too. What i has done to get solution from that is like i find inspiration and imitate how deleting github repository works, i usually choose unique field or something that not really hard to type it like example slug or username etc.

Basically you pass slug for user to see what input must be type then when you `onConfirmed` listener method, you query from slug or unique field to get data then delete it.

**Comment by jantinnerezo** [comment]
Hi @mrl22 @lutfifirdaus 

It's not documented but not sure if you already did this but you can:

``` PHP
public function confirm($id)
{
  $this->confirm('Sure?', [
     'inputAttributes' => [
         'value' => $id
      ],
      'onConfirmed' => 'confirmed' 
  ]);
}

public function confirmed($response)
{
 // Get the id for query
 $id = $response['data']['inputAttributes']['value'];
}
```

**Comment by ISNewton** [comment]
This is not working . Throws the an error in `confirmed`  method : `Unable to resolve dependency [Parameter #0 [ <required> $response ]] in class App\Livewire\Dashboard\Student\StudentProfile`

**Comment by mrl22** [comment]
> This is not working . Throws the an error in `confirmed` method : `Unable to resolve dependency [Parameter #0 [ <required> $response ]] in class App\Livewire\Dashboard\Student\StudentProfile`

This was posted almost two years ago and I am not sure if this method works on newer versions of Livewire. 

I have moved on to generating my own dialogs. Example: https://gist.github.com/mrl22/9d07491b3a84d3e299959ad659c5cec0
