### ISSUE TITLE
Support for alert stacking

### ISSUE THREAD

**Issue by lokmanhakim** [jantinnerezo/livewire-alert#88]
Hi,
I'm trying to fire multiple alert in single API request to a third party, at the start and at the end and when there is an exception. It doesn't seem to stack and only show the latest request

**Comment by jantinnerezo** [comment]
Hi @lokmanhakim 

SweetAlert2 does not support alert stacking

**Comment by yosleydy** [comment]
Hola buenas tardes, como puedo desinstalar ese paquete de mi proyecto?
