### ISSUE TITLE
How can I add dark mode?

### ISSUE THREAD

**Issue by alighasemzadeh** [jantinnerezo/livewire-alert#89]
Hi
I try to add dark mode but always I get a white alert page can anyone help me?

**Comment by jantinnerezo** [comment]
Hi @alighasemzadeh 

Good question,

Well you just need to grab the dark theme CSS, when you are using CDN you can set it up like this:

```html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@5/dark.css" />
```
Also please use this sweetalert2 script CDN
```html
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
```

Please see official doc: https://github.com/sweetalert2/sweetalert2-themes

**Comment by alighasemzadeh** [comment]
@jantinnerezo 
I did it but I get a white alert.

**Comment by jantinnerezo** [comment]
@alighasemzadeh  

This is what I did
<img width="894" alt="image" src="https://user-images.githubusercontent.com/29738837/170875118-9b0b2a91-0574-4622-ae5d-b4c6a2225d5f.png">

Result
<img width="894" alt="image" src="https://user-images.githubusercontent.com/29738837/170875214-130c165b-e2dc-40e4-ac07-7782e3abde38.png">

**Comment by alighasemzadeh** [comment]
How to use it in offline mode?
Build with SCSS and use offline without CDN.

**Comment by jantinnerezo** [comment]
Install it using NPM and then import it into your main javascript file, it's in the sweetalert2 theme docs
