### ISSUE TITLE
Suggestion: $this->alert() returning Boolean ?

### ISSUE THREAD

**Issue by dgillier** [jantinnerezo/livewire-alert#92]
Hi,
great component,

I'm wondering if it will be possible to return a boolean or even an button id, so it will be not needed to listen to events ?
This will make simpler for some basic function as

```
public function delete()
{
   if ($this->alert('warning', 'Alert with ok and cancel button', [
      'showConfirmButton' => true,
      'confirmButtonText' => 'Delete',
      'showCancelButton' => true,
      'cancelButtonText' => 'Cancel',
      'onConfirm' => true,  //returned value if confirm
      'onDismissed' => false,  //returned value if cancel
  ])) delete()...

}
```
What do you think ?
Denis

**Comment by jantinnerezo** [comment]
Hi @dgillier 

It's not possible because Livewire doesn't know if the alert is confirmed or canceled that's why Javascript needs to emit events. It's only possible I think if you display alerts with Javascript not using Livewire.
