### ISSUE TITLE
Passing preConfirm

### ISSUE THREAD

**Issue by PhilBellwood** [jantinnerezo/livewire-alert#95]
Hi

Is there a way to pass preConfirm so that multiple inputs can be added to an alert.
I want to user to pit in an name and email on the alert window.

Maybe there is another way to have multiple inputs to pass values back?

Thank you for your help.

**Comment by jantinnerezo** [comment]
Hi @PhilBellwood 

Currently, there's no way you can pass `preConfirm` the create multiple inputs on alert. I did some digging and I think I can add this feature in future releases.
