### ISSUE TITLE
<x-livewire-alert::scripts /> didn't work on Ubuntu 22.04

### ISSUE THREAD

**Issue by gorimatyan** [jantinnerezo/livewire-alert#98]
This is my first issue so This may be a strange opinion.

I have deployed my application using livewire-alert on Ubuntu 22.04.
When I had developed on Windows10, <x-livewire-alert::scripts /> worked normally.
However, <x-livewire-alert::scripts /> didn't work on Ubuntu 22.04.
↓This is a error message

**Unable to locate a class or view for component [livewire-alert::scripts].**

I guess case-sensitive of Linux is the cause.
Windows and MacOS is insensitive.

Sorry if I'm wrong.

**Comment by jantinnerezo** [comment]
Hi @gorimatyan 

Did you already try ``composer dump-autoload`` or ``php artisan view:clear``?

**Comment by gorimatyan** [comment]
I tried it but doesn't work.

I have tried a lot, as a result, livewire-aleart scripts could work when I used "asset('vendor/livewire-alert/livewire-alert.js')" instead of <x-livewire-alert::scripts /> . Thank you.
