### ISSUE TITLE
How can I show many alerts? Is it possibly ? 

### ISSUE THREAD

**Issue by jcamilovallejos** [jantinnerezo/livewire-alert#99]
I want to show several alerts in my window, Can I do it? Currently, I can show only one notification.

**Comment by jantinnerezo** [comment]
Hi @jcamilovallejos 

Do you mean stacking alerts?

**Comment by jcamilovallejos** [comment]
Yes. Something like in this page https://jacekjeznach.com/portfolio/. You could look at the right bottom in this page, the notifications. I want to try it with sweet alert, but when I declare $this->alert(); $this->alert() only show me the second alert.
